# Generated by Django 4.2.3 on 2023-07-05 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="details",
            field=models.CharField(default="default value", max_length=100),
        ),
        migrations.AddField(
            model_name="services",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
